language: csharp
mono: none
dotnet: 2.1.200

jobs:
  include:
    - name: "Build"
      script:
        - dotnet build
    - name: "Test"
      script:
        - dotnet test ./Tests.XUnitPriorityOrderer/Tests.XUnitPriorityOrderer.csproj